# windows.yml - tasks file for Role-Patch
---

- name: Patch - windows - Install all security, critical, and rollup updates without a scheduled task
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups

...
